language: node_js
node_js:
- stable
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script: CXX=g++-4.8 npm run lint && npm run test

after_success:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - ./scripts/solc-js-publish
